module.exports = {
  someSidebar: {
    Documentation: [
        'install',
        'javascript-arguments',
        'integrating',
        'offline-online-automation',
        'smtp',
        'voice_messages',
        'upgrading',
        'permission',
        'anonymize',
        'paid-chats',
        'product',
        'theme',
        'commands',
        'dashboard',
        'co-browsing',
        'priority',
        'proactive',
        'blocking',
        'canned',
        'leavingmessages',
        'custom-fields-and-prefill',
        'operators-chat',
        'auto-responder',
        'department-transfer',
        'chrome-extension',
        'google-analytics',
        'need-help',
        'redirect-contact-form',
        'invisible-mode',
        'online-hours',
        'auto-assignment',
        'auto-close-delete',
        'online-visitors',
        {
            type: 'category',
            label: 'Bot',
            items: ['how-to-use-bot','bot/bot-text','bot/bot-list','bot/bot-button-list','bot/bot-carousel']
        }
    ],
    Users: ['users/users-groups','users/users-roles','users/users-users','users/users-login-options'],
    Chat: ['chat/chat-status','chat/multiple-domains'],
    Developing: ['hooks',
        'debug',
        {
            type: 'category',
            label: 'Extending',
            items: ['extending/writing-extension','extending/override-module','extending/override-template','development/override-class']
        },
        'development/rest-api',
        'development/move-chat',
        'development/unbrand',
        'nginx-configuration-tips',
        'architecture',
        'performance',
        'back-office-theme',
        'node-js',
        'language',
        'development/auto-login',
        'development/single-sign-on',
        'development/docker',
        'development/cronjob',
        'development/site-access',
        'development/remove-index-php',
        'development/http-and-https'
    ],
    Guides: ['doc1']
  },
};
